import Head from "next/head";
import Articles from "../components/articles/Articles";
import AuthHeader from "../components/AuthHeader";
import Header from "../components/header/Header";
import type { GetStaticProps } from "next";
import prisma from "../lib/prisma";

export default function Home({ articles }: any) {
  console.log(articles);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthHeader />
      <Header />
      <Articles articles={articles} />
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const articles = await prisma.post.findMany({
    where: { published: true },
    include: {
      author: {
        select: { name: true },
      },
    },
  });
  return {
    props: { articles },
    revalidate: 10,
  };
};
